# .streamlit/config.toml
[theme]
base="light"                # “dark” also available
primaryColor="#5842ff"      # brand purple
secondaryBackground="#ffffff"
textColor="#010203"
font="sans serif"           # "serif" or "monospace" if you prefer
